"""
:mod:`etlplus.file.log` module.

Stub helpers for reading/writing generic log (LOG) files (not implemented yet).

Notes
-----
- A LOG file is a plain text file that contains log messages generated by
    applications or systems.
- Common cases:
    - Each line in the file represents a single log entry.
    - Log entries may include timestamps, log levels, and messages.
    - Formats may vary widely depending on the application generating the logs.
- Rule of thumb:
    - If the file is a generic log file, use this module for reading and
        writing.
"""

from __future__ import annotations

from ..types import JSONData
from ..types import JSONList
from ..types import StrPath
from ._io import coerce_path
from .enums import FileFormat
from .stub import StubFileHandlerABC

# SECTION: EXPORTS ========================================================== #


__all__ = [
    # Classes
    'LogFile',
    # Functions
    'read',
    'write',
]


# SECTION: CLASSES ========================================================== #


class LogFile(StubFileHandlerABC):
    """
    Stub handler implementation for LOG files.
    """

    # -- Class Attributes -- #

    format = FileFormat.LOG

    # -- Instance Methods -- #

    # Inherits read() and write() from StubFileHandlerABC.

# SECTION: INTERNAL CONSTANTS ============================================== #


_LOG_HANDLER = LogFile()


# SECTION: FUNCTIONS ======================================================== #


def read(
    path: StrPath,
) -> JSONList:
    """
    Read and return LOG content from *path*.

    Parameters
    ----------
    path : StrPath
        Path to the LOG file on disk.

    Returns
    -------
    JSONList
        The list of dictionaries read from the LOG file.
    """
    return _LOG_HANDLER.read(coerce_path(path))


def write(
    path: StrPath,
    data: JSONData,
) -> int:
    """
    Write *data* to LOG at *path* and return record count.

    Parameters
    ----------
    path : StrPath
        Path to the LOG file on disk.
    data : JSONData
        Data to write as LOG. Should be a list of dictionaries or a
        single dictionary.

    Returns
    -------
    int
        The number of rows written to the LOG file.
    """
    return _LOG_HANDLER.write(coerce_path(path), data)
