# .readthedocs.yaml
# ETLPlus
#
# Copyright © 2026 Dagitali LLC. All rights reserved.
#
# Read the Docs configuration file for Sphinx projects.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

---

# Required.
version: 2

# Set the OS, Python version, & other tools needed for building docs.
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Optional: Build docs in additional formats.
formats:
  - epub
  - pdf

# Build docs in "docs/" directory with Sphinx.
sphinx:
  # Sphinx configuration file path.
  configuration: docs/source/conf.py
  # Fail on all warnings to avoid broken references.
  fail_on_warning: true

# Optional (recommended): Declare Python requirements required to build docs.
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    # Install Python packages before building docs.
    - method: pip
      path: .
      extra_requirements:
        - docs
