# .ruff.toml
# ETLPlus
#
# Copyright © 2026 Dagitali LLC. All rights reserved.
#
# Ruff configuration.
#
# Target Python 3.13, keep it fast and opinionated but not overbearing.

line-length = 79  # 88 is Ruff's default, popularized by Black.
target-version = "py313"
extend-exclude = [
  "etlplus.egg-info",
  "temp",
  "etlplus/*_DEFUNCT",
  "*_FIXED.py",
  "*_NEW.py",
  "*_ORIG.py",
]

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "W",   # pycodestyle warnings
  "B",   # flake8-bugbear
  "I",   # isort
  "UP",  # pyupgrade
]
preview = true
extend-select = [
  "E203",  # Enforce autopep8 slice spacing (no space before ':')
]
ignore = [
  # Prefer NumPy one-line summary then sections; allow docstrings on magic
  # methods to be optional.
  "D105",  # Missing docstring in magic method
]

[lint.isort]
combine-as-imports = false
force-single-line = true

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
