"""
:mod:`etlplus.cli._handlers.init` module.

Starter-project scaffolding helpers for the CLI facade.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from . import _output

# SECTION: EXPORTS ========================================================== #


__all__ = [
    # Functions
    'init_handler',
]


# SECTION: INTERNAL CONSTANTS =============================================== #


_DEFAULT_JOB_NAME = 'file_to_file_customers'
_PIPELINE_PATH = Path('pipeline.yml')
_SAMPLE_INPUT_PATH = Path('data/customers.csv')
_SAMPLE_OUTPUT_DIR = Path('temp')
_SAMPLE_OUTPUT_PATH = _SAMPLE_OUTPUT_DIR / 'customers.json'


# SECTION: INTERNAL FUNCTIONS =============================================== #


def _next_steps(
    root: Path,
) -> list[str]:
    """Return suggested next commands for the initialized project."""
    steps: list[str] = []
    resolved_root = root.resolve()
    if resolved_root != Path.cwd().resolve():
        steps.append(f'cd {resolved_root}')
    steps.extend(
        [
            'etlplus check --config pipeline.yml --jobs',
            'etlplus check --readiness --config pipeline.yml --strict',
            (f'etlplus run --config pipeline.yml --job {_DEFAULT_JOB_NAME}'),
        ],
    )
    return steps


def _pipeline_text() -> str:
    """Return the starter pipeline YAML scaffold."""
    return (
        dedent(
            f"""
        name: Starter Pipeline
        version: "1"

        sources:
          - name: customers_csv
            type: file
            format: csv
            path: "./{_SAMPLE_INPUT_PATH.as_posix()}"

        transforms:
          select_customer_fields:
            select:
              - name
              - email
              - status

        targets:
          - name: customers_json
            type: file
            format: json
            path: "./{_SAMPLE_OUTPUT_PATH.as_posix()}"

        jobs:
          - name: {_DEFAULT_JOB_NAME}
            description: Starter file-to-file example generated by etlplus init
            extract:
              source: customers_csv
            transform:
              pipeline: select_customer_fields
            load:
              target: customers_json
        """,
        ).strip()
        + '\n'
    )


def _sample_csv_text() -> str:
    """Return starter CSV input content."""
    return (
        dedent(
            """
        name,email,status
        Alice Example,alice@example.com,active
        Bob Example,bob@example.com,inactive
        """,
        ).strip()
        + '\n'
    )


def _write_text_file(
    path: Path,
    content: str,
    *,
    force: bool,
) -> None:
    """Write one scaffold text file unless it already exists without force."""
    if path.exists() and path.is_dir():
        raise ValueError(f'Cannot write scaffold file over directory: {path}')
    if path.exists() and not force:
        raise ValueError(
            f'Scaffold file already exists: {path}. Use --force to overwrite it.',
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')


# SECTION: FUNCTIONS ======================================================== #


def init_handler(
    *,
    directory: str = '.',
    force: bool = False,
    pretty: bool = True,
) -> int:
    """
    Scaffold one minimal ETLPlus starter project.

    Parameters
    ----------
    directory : str, optional
        Target directory for the starter files. Defaults to ``'.'``.
    force : bool, optional
        Whether to overwrite existing scaffold files. Defaults to ``False``.
    pretty : bool, optional
        Whether to pretty-print JSON output. Defaults to ``True``.

    Returns
    -------
    int
        CLI exit code indicating success (``0``) or failure (non-zero).

    Raises
    ------
    ValueError
        If the target directory is a file, or if any scaffold file already
        exists and ``force`` is not set.
    """
    root = Path(directory).expanduser()
    if root.exists() and not root.is_dir():
        raise ValueError(f'Init target must be a directory: {root}')

    root.mkdir(parents=True, exist_ok=True)
    data_dir = root / _SAMPLE_INPUT_PATH.parent
    output_dir = root / _SAMPLE_OUTPUT_DIR
    for directory_path in (data_dir, output_dir):
        if directory_path.exists() and not directory_path.is_dir():
            raise ValueError(
                f'Init target requires a directory but found a file: {directory_path}',
            )
        directory_path.mkdir(parents=True, exist_ok=True)

    pipeline_path = root / _PIPELINE_PATH
    sample_input_path = root / _SAMPLE_INPUT_PATH
    _write_text_file(
        pipeline_path,
        _pipeline_text(),
        force=force,
    )
    _write_text_file(
        sample_input_path,
        _sample_csv_text(),
        force=force,
    )

    payload = {
        'status': 'ok',
        'root': str(root.resolve()),
        'directories': [
            str(_SAMPLE_INPUT_PATH.parent),
            str(_SAMPLE_OUTPUT_DIR),
        ],
        'files': [
            str(_PIPELINE_PATH),
            str(_SAMPLE_INPUT_PATH),
        ],
        'job': _DEFAULT_JOB_NAME,
        'next_steps': _next_steps(root),
    }
    return _output.emit_json_payload(payload, pretty=pretty)
